apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-app
  namespace: contact-app
spec:
  replicas: 1
  selector:
    matchLabels: { app: contact-app }
  template:
    metadata:
      labels: { app: contact-app }
    spec:
      containers:
        - name: contact-app
          image: amolamol2403/contact-app:1.0.0
          imagePullPolicy: Always
          ports: [{ containerPort: 3000 }]
          env:
            - name: DATABASE_URL
              value: postgresql://contacts_user:Amol%40321@postgres:5432/contacts
          readinessProbe: { httpGet: { path: /healthz, port: 3000 } }
          livenessProbe: { httpGet: { path: /healthz, port: 3000 } }
---
apiVersion: v1
kind: Service
metadata:
  name: contact-app
  namespace: contact-app
spec:
  type: NodePort
  selector: { app: contact-app }
  ports:
    - port: 80
      targetPort: 3000
